### ISSUE TITLE
From App Link to Website back to App....

### ISSUE THREAD

**Issue by sirvon** [BranchMetrics/Branch-Integration-Guides#9]
Ok, So my user, Ms. Jazzy, has her snazzy refferal link ready to go.
She posts it on Facebook.
Her gf, Ms. Fly, is on her macbook at the time and clicks the referral link on her timeline
because she wants that free money and her other friends are getting paid already.
She lands on the landing page and is about to click the Google Play Store Badge
to DL the app......

So, how is Ms. Jazzy's info ( userid, etc, etc,) that was embedded in her referral link going to carry over from facebook to the web back into the app, when Ms. Fly completes this flow.
And opens the App for the first time on her Nexus 6?

Can you guide me to material that describes this flow or the way to make Ms. Jazzy's info flow from App ---> FB --> Web ---- App.

thanks!

**Comment by aaustin** [comment]
@sirvon In order to pass a referral information through to the app from desktop web, we need to send a Branch link via SMS to the phone. You can use our default text-me-the-app page that we host for you OR you can build your own. If you build your own, you need to use the web SDK function sendSMS. If you call sendSMS from a user who was referred to that page from a Branch link, the referrer information will automatically be inserted into the link that is sent to the user and the referring information will be passed through desktop -> phone -> app.

Hope this helps!

Web SDK:
https://github.com/BranchMetrics/web-sdk
Example Web App:
https://cdn.branch.io/example.html

**Comment by sirvon** [comment]
nice! thanks for your clear and concise help.

off cuff....what is the slickest branchmetrics implementation that adds real business value ($$) to an app you've seen so far....email me sirvon@sirvon.com if that's better.

thanks again!
